pre:
    grayscale: false
    resize: [0, 0]
    type: Pre
split:
    type: ProcessSplit
    tones:
        red: [255, 0, 0]
        blue: [0, 255, 0]
        yellow: [255, 255, 0]
        black: [0, 0, 0]
    threshold: 30
    substrate: [0, 0, 0]
    angles: [15, 75, 0, 45]
halftone:
    type: AMHalftone
    lpi: 55
    dpi: 1200
    ppi: 300
    hardmix: false
dot:
    type: RoundDot
    fill: 0
    gradient: false
    gain: 0.0
    modulate: true
