pre:
    grayscale: false
    resize: [0, 0]
    type: Pre
split:
    type: ProcessSplit
    tones:
        - [0, 255, 255]
        - [255, 0, 255]
        - [255, 255, 0]
        - [0, 0, 0]
    threshold: 30
    substrate: [255, 255, 255]
    angles: [15, 75, 0, 45]
halftone:
    type: AMHalftone
    lpi: 55
    dpi: 1200
    ppi: 300
    hardmix: false
dot:
    type: RoundDot
    gradient: false
    gain: 0.0
    modulate: true
