split:
    type: ProcessSplit
    tones:
        - [0, 255, 255]
        - [255, 0, 255]
        - [255, 255, 0]
        - [0, 0, 0]
    threshold: 30
    substrate: [255, 255, 255]
    angles: [15, 75, 0, 45]
screen:
    type: AMScreen
    lpi: 55
    dpi: 1200
    ppi: 300
dot:
    type: RoundDot
    gain: 0.0
    angle: grid
    size: radius
